import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  businessappSidebar: [{ type: 'autogenerated', dirName: 'businessapp' }],
  adintelSidebar: [{ type: 'autogenerated', dirName: 'adintel' }],
  localseoSidebar: [{ type: 'autogenerated', dirName: 'localseo' }],
  repmanSidebar: [{ type: 'autogenerated', dirName: 'repman' }],
  socialmarketingSidebar: [{ type: 'autogenerated', dirName: 'socialmarketing' }],
  websiteSidebar: [{ type: 'autogenerated', dirName: 'website' }],
  yeswareSidebar: [{ type: 'autogenerated', dirName: 'yesware' }],
};

export default sidebars;
