import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
* Sidebar definition that mirrors the primary navigation inside Business App.
*
* The Business App sidebar (top-level navigation) excludes the **Home** tab.
* All other existing documentation sections are displayed in the identical
* order that users see inside the product, with **My Products** restored as
* the very first item to match the latest in-product navigation.
*
* TOP-LEVEL ORDER
* ───────────────
*   1. My Products
*   2. Inbox
*   3. CRM
*   4. AI
*   5. Executive Report
*   6. My Business
*   7. Store
*   8. Settings
*   9. Administration
*
* Each top-level item uses **autogenerated** mode so that every markdown file
* inside the matching directory is surfaced automatically. This keeps the file
* system as the single source of truth for sub-pages while still giving us
* fine-grained control over the outer tab order.
*/

/**
* Revised sidebar structure (July 9 2025)
* ────────────────────────────────────────
* This configuration now mirrors the latest Business App navigation exactly.
*
* TOP-LEVEL ORDER
*  1. Home
*  2. Inbox
*  3. CRM
*  4. AI
*  5. Campaigns
*  6. Executive Report
*  7. WordPress Hosting
*  8. Yesware
*  9. Local SEO
* 10. Reputation Management
* 11. Social
* 12. Advertising Intelligence
* 13. My Products
* 14. Store
* 15. Automations
* 16. Administration
*
*  ‑ Categories missing full documentation are stubbed with a single
*    placeholder README so links are resolvable. Each stub directory includes
*    an `index.md` that contains a **TODO:** marker for future writers.
*/

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 1. Home
    {
      type: 'category',
      label: 'Home',
      items: [{type: 'autogenerated', dirName: 'overview'}],
      collapsed: false,
    },

    // 2. Inbox
    {type: 'autogenerated', dirName: 'inbox'},

    // 3. CRM (all CRM-related guides and sub-pages)
    {
      type: 'category',
      label: 'CRM',
      items: [{type: 'autogenerated', dirName: 'crm'}],
    },

    // 4. AI (bundles general AI docs plus AI Employees)
    {
      type: 'category',
      label: 'AI',
      items: [
        {type: 'autogenerated', dirName: 'ai'},
        {type: 'autogenerated', dirName: 'ai-employees'},
      ],
    },

    // 5. Campaigns — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'campaigns'},

    // 6. Executive Report
    {type: 'autogenerated', dirName: 'executivereport'},

    // 7. WordPress Hosting — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'wordpress-hosting'},

    // 8. Yesware — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'yesware'},

    // 9. Local SEO — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'local-seo'},

    // 10. Reputation Management — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'reputation-management'},

    // 11. Social — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'social'},

    // 12. Advertising Intelligence — 📄 TODO: add real docs
    {type: 'autogenerated', dirName: 'advertising-intelligence'},

    // 13. My Products
    {type: 'autogenerated', dirName: 'my-products'},

    // 14. Store
    {type: 'autogenerated', dirName: 'store'},

    // 15. Automations — 📄 TODO: relocate existing guides & expand
    {type: 'autogenerated', dirName: 'automations'},

    // 16. Administration
    {type: 'autogenerated', dirName: 'administration'},
  ],
};

export default sidebars;
